# Generated by Django 3.2.6 on 2023-09-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_careers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('email', models.EmailField(max_length=100)),
                ('seniority', models.PositiveIntegerField()),
            ],
        ),
    ]
