# Generated by Django 3.2.6 on 2023-09-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cvs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvs',
            name='seniority',
            field=models.CharField(max_length=100),
        ),
    ]
